#
# Copyright (c) 2019 Broadcom.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Broadcom, Inc. - initial API and implementation
#

name: CI

on:
  push:
    branches:
      - master
      - development
      - release-next
      - fix_strange_edit_issues
  pull_request:
    branches:
      - master
      - development

env:
  CLIENT_DIR: clients/vscode-hlasmplugin

jobs:
  formal-checks:
    name: Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        run: clang-format-14 -style=file -n $(find . -name \*.h -print -o -name \*.cpp -print) 2>&1 | tee clang-format-output.txt
      - name: Check format
        run: |
          if [ -s clang-format-output.txt ]
          then
            exit 1
          fi
      - name: Check license headers
        run: cmake/check_license.sh
      - name: PR to master is allowed only from a release branch
        if: github.event_name == 'pull_request' && github.base_ref == 'master' && github.head_ref != 'release-next'
        run: exit 1

  generate_grammar:
    name: Generate grammar
    runs-on: ubuntu-22.04
    needs: [formal-checks]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: build/generated_parser
          key: ${{ hashFiles('**/CMakeLists.txt', 'cmake/**', 'parser_library/src/parsing/grammar/**') }}
      - name: Set up JDK 11
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Generate grammar
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir build && cd build
          cmake -DBUILD_VSIX=Off -DBUILD_TESTING=Off ../
          cmake --build . --target generate_grammar
      - name: Upload generated files
        uses: actions/upload-artifact@v3
        with:
          name: grammar
          path: build/generated_parser/hlasmparser_*.*

  sanitizer-builds:
    name: Build with sanitizers
    runs-on: ubuntu-22.04
    needs: [generate_grammar]
    strategy:
      matrix:
        include:
          - flags: address,undefined
          - flags: thread

    steps:
      - uses: actions/checkout@v3
      - name: Download generated files
        uses: actions/download-artifact@v3
        with:
          name: grammar
          path: build/generated_parser
      - name: Requirements install
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build
      - name: Configure
        run: cmake -G Ninja -DBUILD_VSIX=Off -DCMAKE_C_COMPILER=clang-14 -DCMAKE_CXX_COMPILER=clang++-14 -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.flags }}" -DWITH_LIBCXX=Off -DUSE_PRE_GENERATED_GRAMMAR="generated_parser" ../
        working-directory: build
      - name: Build
        run: cmake --build .
        working-directory: build
      - name: Test
        run: |
          ./server_test
          ./library_test
          ./hlasm_utils_test
        working-directory: build/bin

  build-matrix:
    name: Build
    runs-on: ${{ matrix.os }}
    needs: [generate_grammar]
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            native: linux
            container: alpine:3.16
            prereq: apk update && apk add --no-cache linux-headers git g++ cmake ninja
            config: cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS="-static" -DBUILD_VSIX=Off -DUSE_PRE_GENERATED_GRAMMAR="generated_parser" ../
            dbg-strip: objcopy --only-keep-debug language_server language_server.dbg && objcopy --strip-unneeded language_server && objcopy --add-gnu-debuglink=language_server.dbg language_server
            dbg-pattern: build/bin/language_server.dbg
          - os: ubuntu-22.04
            native: wasm
            container: emscripten/emsdk:3.1.13
            prereq: sudo apt-get update && sudo apt-get install -y ninja-build
            config: >
              emcmake cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DDISCOVER_TESTS=Off
              -DWITH_LIBCXX=Off -DWITH_STATIC_CRT=Off -DCMAKE_CXX_FLAGS="-s USE_PTHREADS=1 -fexceptions" -DUSE_PRE_GENERATED_GRAMMAR="generated_parser"
              -DCMAKE_EXE_LINKER_FLAGS="-s PTHREAD_POOL_SIZE=8 -s TOTAL_MEMORY=268435456 -s PROXY_TO_PTHREAD=1 -s NODERAWFS=1 -s EXIT_RUNTIME=1 --bind"
              -DCMAKE_CROSSCOMPILING_EMULATOR="node;--experimental-wasm-threads;--experimental-wasm-bulk-memory"
              -Dgtest_disable_pthreads=On -DBUILD_VSIX=Off ../
            test-runner: node --experimental-wasm-threads --experimental-wasm-bulk-memory
            artifacts-ext: .*
          - os: windows-2022
            native: win32
            config: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_VSIX=Off -DUSE_PRE_GENERATED_GRAMMAR="generated_parser" ../
            build-extra: --parallel --config Release
            artifacts-ext: .exe
          - os: macos-12
            native: darwin
            prereq: brew install ninja
            config: cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$(brew --prefix llvm@15)/bin/clang -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@15)/bin/clang++ -DLLVM_PATH=$(brew --prefix llvm@15) -DBUILD_VSIX=Off -DUSE_PRE_GENERATED_GRAMMAR="generated_parser" ../
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
      - name: Download generated files
        uses: actions/download-artifact@v3
        with:
          name: grammar
          path: build/generated_parser
      - name: Requirements install
        if: ${{ matrix.prereq }}
        run: ${{ matrix.prereq }}
      - name: Configure
        run: ${{ matrix.config }}
        working-directory: build
      - name: Build
        run: cmake --build . ${{ matrix.build-extra }}
        working-directory: build
      - name: Server Test
        run: |
          ${{ matrix.test-runner }} ./library_test
          ${{ matrix.test-runner }} ./server_test
          ${{ matrix.test-runner }} ./hlasm_utils_test
        working-directory: build/bin
      - name: Strip debug info
        if: ${{ matrix.dbg-strip }}
        run: ${{ matrix.dbg-strip }}
        working-directory: build/bin
      - name: Actions artifact
        uses: actions/upload-artifact@v3
        with:
          name: language_server_${{ matrix.native }}
          path: build/bin/language_server${{ matrix.artifacts-ext }}
      - name: Actions artifact
        if: ${{ matrix.dbg-pattern }}
        uses: actions/upload-artifact@v3
        with:
          name: language_server_${{ matrix.native }}_dbg
          path: ${{ matrix.dbg-pattern }}

  test-matrix:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: [build-matrix]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            native: linux
            chmod: true
          - os: windows-2019
            native: win32
            chmod: false
          - os: macos-11
            native: darwin
            chmod: true
          - os: ubuntu-22.04
            native: linux
            chmod: true
          - os: windows-2022
            native: win32
            chmod: false
          - os: macos-12
            native: darwin
            chmod: true

    env:
      XVFB: ${{ matrix.native == 'linux' && 'xvfb-run -a' || '' }}
    defaults:
      run:
        working-directory: ${{ env.CLIENT_DIR }}
    steps:
      - uses: actions/checkout@v3
      - name: Download native language server
        uses: actions/download-artifact@v3
        with:
          name: language_server_${{ matrix.native }}
          path: ${{ env.CLIENT_DIR }}/bin/${{ matrix.native }}/
      - name: Download wasm language server
        uses: actions/download-artifact@v3
        with:
          name: language_server_wasm
          path: ${{ env.CLIENT_DIR }}/bin/wasm/
      - name: Set executable flag
        if: ${{ matrix.chmod }}
        run: chmod +x bin/${{ matrix.native }}/language_server
      - name: NPM CI
        run: npm ci
      - name: Extension Test
        run: ${{ env.XVFB }} npm run test
      - name: Extension Test WASM
        run: ${{ env.XVFB }} npm run test:wasm
      - name: Extension Test Insiders
        run: ${{ env.XVFB }} npm run test:insiders

  VSIX:
    runs-on: ubuntu-22.04
    needs: [build-matrix]

    steps:
      - uses: actions/checkout@v3
      - name: Download windows language server
        uses: actions/download-artifact@v3
        with:
          name: language_server_win32
          path: ${{ env.CLIENT_DIR }}/bin/win32/
      - name: Download linux language server
        uses: actions/download-artifact@v3
        with:
          name: language_server_linux
          path: ${{ env.CLIENT_DIR }}/bin/linux/
      - name: Download wasm language server
        uses: actions/download-artifact@v3
        with:
          name: language_server_wasm
          path: ${{ env.CLIENT_DIR }}/bin/wasm/
      - name: Download MacOS language server
        uses: actions/download-artifact@v3
        with:
          name: language_server_darwin
          path: ${{ env.CLIENT_DIR }}/bin/darwin/
      - name: Set executable flag
        run: |
          chmod +x ${{ env.CLIENT_DIR }}/bin/darwin/language_server
          chmod +x ${{ env.CLIENT_DIR }}/bin/linux/language_server
      - name: NPM CI
        run: npm ci
        working-directory: ${{ env.CLIENT_DIR }}
      - name: Inject telemetry key
        run: |
          export TEL_KEY=`node -e "console.log(Buffer.from('${{ secrets.TELEMETRY_KEY }}').toString('base64'))"`
          sed -i "s/const TELEMETRY_KEY_ENCODED = TELEMETRY_DEFAULT_KEY/const TELEMETRY_KEY_ENCODED = '$TEL_KEY'/" src/telemetry.ts
        working-directory: ${{ env.CLIENT_DIR }}
      - name: NPM Compile
        run: npm run compile
        working-directory: ${{ env.CLIENT_DIR }}
      - name: Update version
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release-next'
        run: npx semantic-release --dry-run
        working-directory: ${{ env.CLIENT_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package VSIX
        run: npx vsce package -o hlasm-language-support.vsix --baseContentUrl "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/"
        working-directory: ${{ env.CLIENT_DIR }}
      - name: Upload VSIX
        uses: actions/upload-artifact@v3
        with:
          name: hlasm-language-support.vsix
          path: ${{ env.CLIENT_DIR }}/hlasm-language-support.vsix
      - name: Upload Release Info
        uses: actions/upload-artifact@v3
        with:
          name: release-info
          path: |
            CHANGELOG.md
            ${{ env.CLIENT_DIR }}/package.json
            ${{ env.CLIENT_DIR }}/CHANGELOG.md

  release:
    name: Release VSIXs
    runs-on: ubuntu-22.04
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'push' && github.ref == 'refs/heads/release-next')
    needs: [VSIX, test-matrix, sanitizer-builds, theia-test]

    steps:
      - uses: actions/checkout@v3
      - name: Download VSIX
        uses: actions/download-artifact@v3
        with:
          name: hlasm-language-support.vsix
          path: ${{ env.CLIENT_DIR }}
      - name: Download Release Info
        uses: actions/download-artifact@v3
        with:
          name: release-info
      - name: Commit changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add CHANGELOG.md ${{ env.CLIENT_DIR }}/package.json ${{ env.CLIENT_DIR }}/CHANGELOG.md
          git commit -m "chore: Update version & changelog [skip ci]"
      - name: Push changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: NPM CI
        run: npm ci
        working-directory: ${{ env.CLIENT_DIR }}
      - name: Release new version
        run: npx semantic-release
        working-directory: ${{ env.CLIENT_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge master into development
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git stash
          git fetch
          git checkout origin/development
          git merge origin/master

          cd ${{ env.CLIENT_DIR }}
          sed -i 's/"version": "\(.*\)"/"version": "\1-NEXT"/g' package.json
          sed -i '2s/^/\n## ****Unreleased****\n/' CHANGELOG.md
          git add package.json CHANGELOG.md
          git commit -m "chore: Prepare for next development cycle [skip ci]"
      - name: Push changes
        if: github.event_name == 'push'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
      - name: Delete PRs head branches
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: release-next

  theia-test:
    name: Theia Integration Test
    runs-on: ubuntu-22.04
    needs: VSIX
    strategy:
      matrix:
        theia: ["quay.io/zowe-explorer/theia:1.25.0"] 
# theiaide images not supported anymore, replaced with a quay mirror until there is something official again. See also https://github.com/theia-ide/theia-apps/issues/496
    container:
      image: ${{ matrix.theia }}
      options: --user root

    steps:
      - name: Workaround for git safe.directory feature
        run: chown root:root .
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Chromium
        run: apk add --no-cache chromium
      - name: Download VSIX
        uses: actions/download-artifact@v3
        with:
          name: hlasm-language-support.vsix
          path: ${{ env.CLIENT_DIR }}/plugin/
      - name: npm ci
        run: npm ci
        working-directory: ${{ env.CLIENT_DIR }}
      - name: Run Theia Tests
        run: npm run test:theia /home/theia/
        working-directory: ${{ env.CLIENT_DIR }}
