#
# Copyright (c) 2019 Broadcom.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Broadcom, Inc. - initial API and implementation
#

name: CI

on:
  push:
    branches:
      - master
      - development
      - release-next
      - fix_strange_edit_issues
  pull_request:
    branches:
      - master
      - development

env:
  CLIENT_DIR: clients/vscode-hlasmplugin

jobs:
  test-matrix:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            native: linux
            chmod: true
          - os: windows-2019
            native: win32
            chmod: false
          - os: macos-11
            native: darwin
            chmod: true
          - os: ubuntu-22.04
            native: linux
            chmod: true
          - os: windows-2022
            native: win32
            chmod: false
          - os: macos-12
            native: darwin
            chmod: true

    env:
      XVFB: ${{ matrix.native == 'linux' && 'xvfb-run -a' || '' }}
    defaults:
      run:
        working-directory: ${{ env.CLIENT_DIR }}
    steps:
      - uses: actions/checkout@v3
      - name: Download language servers
        run: |
          wget "https://github.com/eclipse/che-che4z-lsp-for-hlasm/releases/download/1.6.0/hlasm-language-support-1.6.0.vsix"
          unzip -o hlasm-language-support-1.6.0.vsix 'extension/bin/*'
          cp -r extension/bin ./
      - name: Set executable flag
        if: ${{ matrix.chmod }}
        run: chmod +x bin/${{ matrix.native }}/language_server
      - name: NPM CI
        run: npm ci
      - name: Extension Test
        run: ${{ env.XVFB }} npm run test
      - name: Extension Test WASM
        run: ${{ env.XVFB }} npm run test:wasm
      - name: Extension Test Insiders
        run: ${{ env.XVFB }} npm run test:insiders
